# Generated by Django 5.2.7 on 2025-11-19 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_slug_alter_condition_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deed',
            name='file',
        ),
        migrations.CreateModel(
            name='DeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deed/')),
                ('deed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.deed')),
            ],
        ),
    ]
