# Generated by Django 5.2.7 on 2025-11-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_department_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='moc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
