# Generated by Django 5.2.7 on 2025-11-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_employee_full_name_alter_deed_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technics',
            name='condition',
        ),
        migrations.AddField(
            model_name='technics',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('free', "Bo'sh"), ('defect', 'Brak'), ('repair', 'Ta’mirda')], default='free', max_length=20),
        ),
    ]
