# Generated by Django 5.2.7 on 2025-11-19 10:10

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_deed_file_deedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedfile',
            name='file',
            field=models.FileField(upload_to='deed/', validators=[main.validators.validate_file_extension]),
        ),
    ]
