# Generated by Django 5.2.7 on 2025-11-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_deedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deed',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='deed',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='main.employee'),
        ),
    ]
