# Generated by Django 5.2.7 on 2025-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_technics_condition_technics_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deed',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
