# Generated by Django 5.2.7 on 2025-11-05 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_author_alter_department_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_creat',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 11, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='date_edit',
            field=models.DateField(auto_now=True),
        ),
    ]
