# Generated by Django 5.2.7 on 2025-11-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_deed_receiver_alter_deed_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='sender_seen',
            field=models.BooleanField(default=False),
        ),
    ]
