# Generated by Django 5.2.7 on 2025-11-05 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_date_creat_category_date_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='date_creat',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 11, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='date_edit',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='date_creat',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 11, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='date_edit',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='position',
            name='date_creat',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 11, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='date_edit',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='date_creat',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 11, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rank',
            name='date_edit',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='region',
            name='date_creat',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 11, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='date_edit',
            field=models.DateField(auto_now=True),
        ),
    ]
