# Generated by Django 5.2.7 on 2025-11-18 14:32

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_deed_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deed',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='deeds/', validators=[main.validators.validate_file_extension]),
        ),
    ]
