# Generated by Django 5.2.7 on 2025-11-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_deed_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deed',
            name='file',
            field=models.FileField(upload_to='deed/'),
        ),
    ]
