# Generated by Django 5.2.7 on 2025-11-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_deed_sender_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deed',
            old_name='message',
            new_name='message_receiver',
        ),
        migrations.AddField(
            model_name='deed',
            name='message_sender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
