# Generated by Django 5.2.7 on 2025-11-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_employee_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='technics',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
