# Generated by Django 5.2.7 on 2025-11-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technics',
            old_name='model',
            new_name='Inventory',
        ),
    ]
