# Generated by Django 5.2.7 on 2025-11-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_model_technics_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technics',
            old_name='Inventory',
            new_name='inventory',
        ),
    ]
