# Generated by Django 5.2.7 on 2025-11-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_employee_is_staff_remove_technics_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
